FROM eclipse-temurin:21-jre

LABEL maintainer="Suhail Akhtar"
LABEL service="notification-service"

WORKDIR /app

COPY target/notification-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8085

ENTRYPOINT ["java","-jar","app.jar"]