server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sentinelpay
    username: root
    password: suhail
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: mySuperSecretKeyForJwtToken123456