name: Backend CI/CD

on:
  push:
    branches:
      - master

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:

      ####################################################
      # Checkout
      ####################################################

      - name: Checkout Repository
        uses: actions/checkout@v4

      ####################################################
      # Setup Java
      ####################################################

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      ####################################################
      # Install Common Library
      ####################################################

      - name: Install common-lib
        working-directory: sentinel-pay-be/common-lib
        run: mvn clean install -DskipTests

      ####################################################
      # Build JARs
      ####################################################

      - name: Build Auth Service
        working-directory: sentinel-pay-be/auth-service
        run: mvn clean package -DskipTests

      - name: Build Wallet Service
        working-directory: sentinel-pay-be/Wallet-Service
        run: mvn clean package -DskipTests

      - name: Build Payment Service
        working-directory: sentinel-pay-be/payment-service
        run: mvn clean package -DskipTests

      - name: Build Fraud Service
        working-directory: sentinel-pay-be/fraud-service
        run: mvn clean package -DskipTests

      - name: Build Notification Service
        working-directory: sentinel-pay-be/notification-service
        run: mvn clean package -DskipTests

      - name: Build Ledger Service
        working-directory: sentinel-pay-be/ledger-service
        run: mvn clean package -DskipTests

      - name: Build API Gateway
        working-directory: sentinel-pay-be/api-gateway
        run: mvn clean package -DskipTests

      ####################################################
      # Login to Docker Hub
      ####################################################

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ####################################################
      # Build & Push Auth Image
      ####################################################

      - name: Build & Push Auth Image
        working-directory: sentinel-pay-be/auth-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      ####################################################
      # Build & Push Wallet Image
      ####################################################

      - name: Build & Push Wallet Image
        working-directory: sentinel-pay-be/Wallet-Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wallet-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/wallet-service:latest

      ####################################################
      # Build & Push Payment Image
      ####################################################

      - name: Build & Push Payment Image
        working-directory: sentinel-pay-be/payment-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:latest

      ####################################################
      # Build & Push Fraud Image
      ####################################################

      - name: Build & Push Fraud Image
        working-directory: sentinel-pay-be/fraud-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fraud-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fraud-service:latest

      ####################################################
      # Build & Push Notification Image
      ####################################################

      - name: Build & Push Notification Image
        working-directory: sentinel-pay-be/notification-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

      ####################################################
      # Build & Push Ledger Image
      ####################################################

      - name: Build & Push Ledger Image
        working-directory: sentinel-pay-be/ledger-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ledger-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ledger-service:latest

      ####################################################
      # Build & Push API Gateway Image
      ####################################################

      - name: Build & Push API Gateway Image
        working-directory: sentinel-pay-be/api-gateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest